// ============================================
// MOCK DATA - Synthetic Example Infrastructure
// ============================================
// This file contains synthetic mock data for demonstration purposes.
// All service names, team names, costs, and metrics are completely fictional
// and generated for visualization examples only.
//
// DO NOT commit real infrastructure data to public repositories.
// DO NOT include:
// - Real team names or personnel information
// - Real service names or internal architecture
// - Real cost data
// - Real API keys, tokens, or secrets
// - Real email addresses
// - Real region/datacenter information
// ============================================

export const mockResources = [
  // ===== APPLICATION LAYER (15 services) =====
  {
    id: 'svc-api-001',
    name: 'Service API 001',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Alpha',
    cost30d: 450,
    healthScore: 98,
    status: 'healthy',
    dependencies: ['db-001', 'cache-001', 'gateway-001'],
    lastModified: new Date(Date.now() - 2 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['api', 'critical', 'service'],
    telemetry: {
      latency: 45,
      rps: 2500,
      errorRate: 0.02,
      cpuUsage: 78,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-auth-002',
    name: 'Service Auth 002',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Beta',
    cost30d: 280,
    healthScore: 99,
    status: 'healthy',
    dependencies: ['db-002', 'vault-001', 'gateway-001'],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['auth', 'security', 'critical'],
    telemetry: {
      latency: 38,
      rps: 1800,
      errorRate: 0.005,
      cpuUsage: 32,
      memoryUsage: 41,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-notif-003',
    name: 'Service Notify 003',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Gamma',
    cost30d: 180,
    healthScore: 72,
    status: 'failing',
    dependencies: ['queue-001', 'queue-002'],
    lastModified: new Date(Date.now() - 1 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['notification', 'messaging'],
    telemetry: {
      latency: 520,
      rps: 450,
      errorRate: 0.45,
      cpuUsage: 5,
      memoryUsage: 15,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-order-004',
    name: 'Service Order 004',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Delta',
    cost30d: 320,
    healthScore: 95,
    status: 'healthy',
    dependencies: ['db-003', 'svc-api-001', 'svc-inv-005'],
    lastModified: new Date(Date.now() - 4 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['orders', 'critical', 'business'],
    telemetry: {
      latency: 62,
      rps: 1200,
      errorRate: 0.015,
      cpuUsage: 45,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-inv-005',
    name: 'Service Inventory 005',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Epsilon',
    cost30d: 220,
    healthScore: 88,
    status: 'healthy',
    dependencies: ['db-004', 'cache-002'],
    lastModified: new Date(Date.now() - 5 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['inventory', 'service'],
    telemetry: {
      latency: 95,
      rps: 600,
      errorRate: 0.01,
      cpuUsage: 34,
      memoryUsage: 48,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-report-006',
    name: 'Service Report 006',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Zeta',
    cost30d: 150,
    healthScore: 91,
    status: 'healthy',
    dependencies: ['db-analytics', 'cache-003'],
    lastModified: new Date(Date.now() - 8 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['analytics', 'reporting'],
    telemetry: {
      latency: 180,
      rps: 200,
      errorRate: 0.005,
      cpuUsage: 28,
      memoryUsage: 35,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-user-007',
    name: 'Service User 007',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Beta',
    cost30d: 190,
    healthScore: 96,
    status: 'healthy',
    dependencies: ['db-005', 'cache-001', 'svc-auth-002'],
    lastModified: new Date(Date.now() - 3 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['users', 'critical'],
    telemetry: {
      latency: 52,
      rps: 1500,
      errorRate: 0.008,
      cpuUsage: 42,
      memoryUsage: 54,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-webhook-008',
    name: 'Service Webhook 008',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Gamma',
    cost30d: 130,
    healthScore: 93,
    status: 'degraded',
    dependencies: ['queue-001', 'queue-003'],
    lastModified: new Date(Date.now() - 6 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['webhooks', 'integration'],
    telemetry: {
      latency: 340,
      rps: 800,
      errorRate: 0.08,
      cpuUsage: 56,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-search-009',
    name: 'Service Search 009',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Delta',
    cost30d: 240,
    healthScore: 89,
    status: 'healthy',
    dependencies: ['search-index-001', 'cache-004'],
    lastModified: new Date(Date.now() - 12 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['search', 'service'],
    telemetry: {
      latency: 125,
      rps: 950,
      errorRate: 0.012,
      cpuUsage: 67,
      memoryUsage: 71,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-payment-010',
    name: 'Service Payment 010',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Epsilon',
    cost30d: 380,
    healthScore: 99,
    status: 'healthy',
    dependencies: ['db-006', 'gateway-002', 'vault-002'],
    lastModified: new Date(Date.now() - 24 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['payment', 'critical', 'financial'],
    telemetry: {
      latency: 48,
      rps: 3200,
      errorRate: 0.003,
      cpuUsage: 81,
      memoryUsage: 68,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-admin-011',
    name: 'Service Admin 011',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Zeta',
    cost30d: 165,
    healthScore: 92,
    status: 'healthy',
    dependencies: ['db-007', 'audit-log-001'],
    lastModified: new Date(Date.now() - 48 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['admin', 'management'],
    telemetry: {
      latency: 89,
      rps: 300,
      errorRate: 0.006,
      cpuUsage: 22,
      memoryUsage: 38,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-config-012',
    name: 'Service Config 012',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Alpha',
    cost30d: 95,
    healthScore: 97,
    status: 'healthy',
    dependencies: ['config-store-001', 'cache-005'],
    lastModified: new Date(Date.now() - 36 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['config', 'service'],
    telemetry: {
      latency: 15,
      rps: 5000,
      errorRate: 0.001,
      cpuUsage: 18,
      memoryUsage: 24,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-metrics-013',
    name: 'Service Metrics 013',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Gamma',
    cost30d: 210,
    healthScore: 85,
    status: 'healthy',
    dependencies: ['metrics-db-001', 'cache-006'],
    lastModified: new Date(Date.now() - 18 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['metrics', 'monitoring'],
    telemetry: {
      latency: 145,
      rps: 400,
      errorRate: 0.018,
      cpuUsage: 52,
      memoryUsage: 59,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-logging-014',
    name: 'Service Logging 014',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Delta',
    cost30d: 175,
    healthScore: 94,
    status: 'healthy',
    dependencies: ['log-store-001', 'queue-004'],
    lastModified: new Date(Date.now() - 9 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['logging', 'observability'],
    telemetry: {
      latency: 75,
      rps: 8000,
      errorRate: 0.005,
      cpuUsage: 64,
      memoryUsage: 72,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-tracer-015',
    name: 'Service Tracer 015',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Epsilon',
    cost30d: 145,
    healthScore: 96,
    status: 'healthy',
    dependencies: ['trace-store-001', 'cache-007'],
    lastModified: new Date(Date.now() - 14 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['tracing', 'observability'],
    telemetry: {
      latency: 68,
      rps: 6500,
      errorRate: 0.004,
      cpuUsage: 58,
      memoryUsage: 61,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  // NEW APPLICATION SERVICES
  {
    id: 'svc-billing-016',
    name: 'Service Billing 016',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Zeta',
    cost30d: 285,
    healthScore: 87,
    status: 'degraded',
    dependencies: ['db-008', 'queue-002', 'vault-001'],
    lastModified: new Date(Date.now() - 8 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['billing', 'financial', 'critical'],
    telemetry: {
      latency: 95,
      rps: 600,
      errorRate: 0.025,
      cpuUsage: 72,
      memoryUsage: 68,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-analytics-017',
    name: 'Service Analytics 017',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Alpha',
    cost30d: 195,
    healthScore: 92,
    status: 'healthy',
    dependencies: ['db-009', 'queue-006'],
    lastModified: new Date(Date.now() - 11 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['analytics', 'reporting', 'data-processing'],
    telemetry: {
      latency: 195,
      rps: 350,
      errorRate: 0.008,
      cpuUsage: 48,
      memoryUsage: 55,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-recommendation-018',
    name: 'Service Recommendation 018',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Beta',
    cost30d: 325,
    healthScore: 72,
    status: 'failing',
    dependencies: ['db-010', 'cache-005', 'svc-api-001', 'svc-user-007'],
    lastModified: new Date(Date.now() - 2 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['recommendations', 'ml', 'critical'],
    telemetry: {
      latency: 85,
      rps: 250,
      errorRate: 0.08,
      cpuUsage: 88,
      memoryUsage: 82,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-export-019',
    name: 'Service Export 019',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Gamma',
    cost30d: 155,
    healthScore: 85,
    status: 'degraded',
    dependencies: ['queue-005', 'svc-report-006'],
    lastModified: new Date(Date.now() - 5 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['export', 'data-pipeline'],
    telemetry: {
      latency: 350,
      rps: 200,
      errorRate: 0.04,
      cpuUsage: 68,
      memoryUsage: 71,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-cache-mgmt-020',
    name: 'Service Cache Manager 020',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Delta',
    cost30d: 110,
    healthScore: 94,
    status: 'healthy',
    dependencies: ['cache-001', 'cache-002', 'cache-003', 'cache-004', 'cache-005', 'cache-006', 'cache-007'],
    lastModified: new Date(Date.now() - 16 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['cache', 'management', 'performance'],
    telemetry: {
      latency: 8,
      rps: 12000,
      errorRate: 0.002,
      cpuUsage: 55,
      memoryUsage: 48,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-session-021',
    name: 'Service Session 021',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Epsilon',
    cost30d: 205,
    healthScore: 91,
    status: 'healthy',
    dependencies: ['cache-001', 'db-002'],
    lastModified: new Date(Date.now() - 20 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['session', 'user-state', 'critical'],
    telemetry: {
      latency: 12,
      rps: 3500,
      errorRate: 0.005,
      cpuUsage: 51,
      memoryUsage: 59,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-rate-limit-022',
    name: 'Service Rate Limiter 022',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Zeta',
    cost30d: 85,
    healthScore: 99,
    status: 'healthy',
    dependencies: ['cache-002', 'gateway-001', 'gateway-002'],
    lastModified: new Date(Date.now() - 24 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['rate-limiting', 'gateway', 'protection'],
    telemetry: {
      latency: 4,
      rps: 20000,
      errorRate: 0.001,
      cpuUsage: 38,
      memoryUsage: 42,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-notification-023',
    name: 'Service Notification 023',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Alpha',
    cost30d: 135,
    healthScore: 88,
    status: 'degraded',
    dependencies: ['queue-001', 'queue-004', 'cache-003'],
    lastModified: new Date(Date.now() - 3 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['notifications', 'messaging', 'async'],
    telemetry: {
      latency: 125,
      rps: 1200,
      errorRate: 0.035,
      cpuUsage: 62,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-document-024',
    name: 'Service Document 024',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Beta',
    cost30d: 165,
    healthScore: 93,
    status: 'healthy',
    dependencies: ['db-007', 'search-index-001', 'cache-006'],
    lastModified: new Date(Date.now() - 7 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['document', 'storage', 'search'],
    telemetry: {
      latency: 75,
      rps: 450,
      errorRate: 0.012,
      cpuUsage: 45,
      memoryUsage: 52,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-workflow-025',
    name: 'Service Workflow 025',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Gamma',
    cost30d: 125,
    healthScore: 84,
    status: 'degraded',
    dependencies: ['queue-003', 'queue-005', 'db-008'],
    lastModified: new Date(Date.now() - 4 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['workflow', 'orchestration', 'async'],
    telemetry: {
      latency: 245,
      rps: 300,
      errorRate: 0.052,
      cpuUsage: 58,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },

  // ===== INFRASTRUCTURE LAYER (12 services) =====
  {
    id: 'gateway-001',
    name: 'API Gateway 001',
    type: 'API Gateway',
    region: 'Region A',
    owner: 'Infra Team',
    cost30d: 280,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['gateway', 'critical', 'ingress'],
    telemetry: {
      latency: 5,
      rps: 15000,
      errorRate: 0.001,
      cpuUsage: 45,
      memoryUsage: 38,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'gateway-002',
    name: 'API Gateway 002',
    type: 'API Gateway',
    region: 'Region B',
    owner: 'Infra Team',
    cost30d: 270,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['gateway', 'critical', 'ingress'],
    telemetry: {
      latency: 6,
      rps: 12000,
      errorRate: 0.002,
      cpuUsage: 42,
      memoryUsage: 36,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'lb-001',
    name: 'Load Balancer 001',
    type: 'Load Balancer',
    region: 'Region A',
    owner: 'Infra Team',
    cost30d: 120,
    healthScore: 100,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 240 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['load-balancer', 'critical'],
    telemetry: {
      latency: 2,
      rps: 20000,
      errorRate: 0.0,
      cpuUsage: 35,
      memoryUsage: 28,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'kube-001',
    name: 'Kubernetes Cluster 001',
    type: 'Orchestration',
    region: 'Region A',
    owner: 'Platform Team',
    cost30d: 450,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['kubernetes', 'orchestration', 'critical'],
    telemetry: {
      latency: 8,
      rps: 10000,
      errorRate: 0.003,
      cpuUsage: 62,
      memoryUsage: 71,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'kube-002',
    name: 'Kubernetes Cluster 002',
    type: 'Orchestration',
    region: 'Region B',
    owner: 'Platform Team',
    cost30d: 420,
    healthScore: 96,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 120 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['kubernetes', 'orchestration', 'critical'],
    telemetry: {
      latency: 9,
      rps: 9000,
      errorRate: 0.004,
      cpuUsage: 68,
      memoryUsage: 74,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'kube-003',
    name: 'Kubernetes Cluster 003',
    type: 'Orchestration',
    region: 'Region C',
    owner: 'Platform Team',
    cost30d: 400,
    healthScore: 94,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['kubernetes', 'orchestration', 'critical'],
    telemetry: {
      latency: 11,
      rps: 8500,
      errorRate: 0.005,
      cpuUsage: 72,
      memoryUsage: 76,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'service-mesh-001',
    name: 'Service Mesh 001',
    type: 'Service Mesh',
    region: 'Global',
    owner: 'Platform Team',
    cost30d: 280,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 96 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['service-mesh', 'istio', 'networking'],
    telemetry: {
      latency: 1,
      rps: 50000,
      errorRate: 0.0005,
      cpuUsage: 45,
      memoryUsage: 52,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'lb-002',
    name: 'Load Balancer 002',
    type: 'Load Balancer',
    region: 'Region B',
    owner: 'Infra Team',
    cost30d: 110,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 216 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['load-balancer', 'critical'],
    telemetry: {
      latency: 2,
      rps: 18000,
      errorRate: 0.001,
      cpuUsage: 38,
      memoryUsage: 31,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'gateway-003',
    name: 'API Gateway 003',
    type: 'API Gateway',
    region: 'Region C',
    owner: 'Infra Team',
    cost30d: 260,
    healthScore: 96,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['gateway', 'critical', 'ingress'],
    telemetry: {
      latency: 7,
      rps: 8000,
      errorRate: 0.003,
      cpuUsage: 44,
      memoryUsage: 38,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'gateway-004',
    name: 'API Gateway 004',
    type: 'API Gateway',
    region: 'Region A',
    owner: 'Infra Team',
    cost30d: 250,
    healthScore: 95,
    status: 'degraded',
    dependencies: [],
    lastModified: new Date(Date.now() - 6 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['gateway', 'critical', 'ingress'],
    telemetry: {
      latency: 8,
      rps: 5000,
      errorRate: 0.008,
      cpuUsage: 52,
      memoryUsage: 45,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'alerting-001',
    name: 'Alerting System 001',
    type: 'Alerting',
    region: 'Region A',
    owner: 'DevOps Team',
    cost30d: 125,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['alerting', 'observability', 'critical'],
    telemetry: {
      latency: 95,
      rps: 1500,
      errorRate: 0.004,
      cpuUsage: 35,
      memoryUsage: 42,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'api-mock-026',
    name: 'API Mock Server 026',
    type: 'Mock Server',
    region: 'Region C',
    owner: 'QA Team',
    cost30d: 65,
    healthScore: 92,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 48 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['testing', 'mock', 'qa'],
    telemetry: {
      latency: 15,
      rps: 3000,
      errorRate: 0.005,
      cpuUsage: 28,
      memoryUsage: 35,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'registry-001',
    name: 'Container Registry 001',
    type: 'Registry',
    region: 'Region A',
    owner: 'Platform Team',
    cost30d: 85,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 216 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['registry', 'storage'],
    telemetry: {
      latency: 150,
      rps: 500,
      errorRate: 0.001,
      cpuUsage: 25,
      memoryUsage: 32,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'vault-001',
    name: 'Secrets Vault 001',
    type: 'Secrets Management',
    region: 'Region A',
    owner: 'Team Iota',
    cost30d: 95,
    healthScore: 100,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 300 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['secrets', 'security', 'critical'],
    telemetry: {
      latency: 28,
      rps: 4000,
      errorRate: 0.0,
      cpuUsage: 18,
      memoryUsage: 22,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'vault-002',
    name: 'Secrets Vault 002',
    type: 'Secrets Management',
    region: 'Region B',
    owner: 'Team Iota',
    cost30d: 95,
    healthScore: 100,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 312 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['secrets', 'security', 'critical'],
    telemetry: {
      latency: 29,
      rps: 3800,
      errorRate: 0.0,
      cpuUsage: 16,
      memoryUsage: 21,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'monitoring-001',
    name: 'Monitoring System 001',
    type: 'Monitoring',
    region: 'Region A',
    owner: 'DevOps Team',
    cost30d: 220,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 96 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['monitoring', 'observability', 'critical'],
    telemetry: {
      latency: 85,
      rps: 2000,
      errorRate: 0.005,
      cpuUsage: 48,
      memoryUsage: 52,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'logging-infra-001',
    name: 'Logging Infrastructure 001',
    type: 'Logging',
    region: 'Region B',
    owner: 'DevOps Team',
    cost30d: 310,
    healthScore: 95,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['logging', 'observability'],
    telemetry: {
      latency: 120,
      rps: 15000,
      errorRate: 0.008,
      cpuUsage: 71,
      memoryUsage: 78,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cdn-001',
    name: 'Content Delivery 001',
    type: 'CDN',
    region: 'Global',
    owner: 'Infra Team',
    cost30d: 350,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['cdn', 'performance', 'critical'],
    telemetry: {
      latency: 12,
      rps: 50000,
      errorRate: 0.001,
      cpuUsage: 38,
      memoryUsage: 44,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },

  // ===== DATA LAYER (14 services) =====
  {
    id: 'db-001',
    name: 'Database 001',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 520,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 240 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'critical'],
    telemetry: {
      latency: 12,
      rps: 5000,
      errorRate: 0.001,
      cpuUsage: 52,
      memoryUsage: 68,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-002',
    name: 'Database 002',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 480,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 264 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'critical'],
    telemetry: {
      latency: 11,
      rps: 4500,
      errorRate: 0.0005,
      cpuUsage: 48,
      memoryUsage: 65,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-003',
    name: 'Database 003',
    type: 'SQL Database',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 440,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 35,
      rps: 2800,
      errorRate: 0.003,
      cpuUsage: 44,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-004',
    name: 'Database 004',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 390,
    healthScore: 96,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 216 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 28,
      rps: 2000,
      errorRate: 0.002,
      cpuUsage: 38,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-005',
    name: 'Database 005',
    type: 'SQL Database',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 410,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 22,
      rps: 3200,
      errorRate: 0.001,
      cpuUsage: 41,
      memoryUsage: 60,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-006',
    name: 'Database 006',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 540,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 288 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'financial'],
    telemetry: {
      latency: 15,
      rps: 6000,
      errorRate: 0.0005,
      cpuUsage: 58,
      memoryUsage: 72,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-007',
    name: 'Database 007',
    type: 'SQL Database',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 370,
    healthScore: 95,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 312 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 42,
      rps: 1200,
      errorRate: 0.005,
      cpuUsage: 32,
      memoryUsage: 52,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-001',
    name: 'Cache 001',
    type: 'Cache',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 180,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 120 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 3,
      rps: 20000,
      errorRate: 0.001,
      cpuUsage: 62,
      memoryUsage: 74,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-002',
    name: 'Cache 002',
    type: 'Cache',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 170,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 96 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 4,
      rps: 18000,
      errorRate: 0.002,
      cpuUsage: 58,
      memoryUsage: 70,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-001',
    name: 'Message Queue 001',
    type: 'Message Queue',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 140,
    healthScore: 94,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'async'],
    telemetry: {
      latency: 45,
      rps: 5000,
      errorRate: 0.008,
      cpuUsage: 44,
      memoryUsage: 56,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-002',
    name: 'Message Queue 002',
    type: 'Message Queue',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 135,
    healthScore: 92,
    status: 'degraded',
    dependencies: [],
    lastModified: new Date(Date.now() - 48 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'async'],
    telemetry: {
      latency: 65,
      rps: 4200,
      errorRate: 0.015,
      cpuUsage: 52,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'search-index-001',
    name: 'Search Index 001',
    type: 'Search Engine',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 210,
    healthScore: 91,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['search', 'elasticsearch', 'indexing'],
    telemetry: {
      latency: 110,
      rps: 2500,
      errorRate: 0.012,
      cpuUsage: 68,
      memoryUsage: 76,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-analytics',
    name: 'Analytics Database',
    type: 'Analytics',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 290,
    healthScore: 88,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['analytics', 'warehouse', 'bigdata'],
    telemetry: {
      latency: 250,
      rps: 150,
      errorRate: 0.02,
      cpuUsage: 72,
      memoryUsage: 85,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },

  // NEW DATA LAYER RESOURCES
  {
    id: 'db-008',
    name: 'Database 008',
    type: 'SQL Database',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 460,
    healthScore: 94,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'financial'],
    telemetry: {
      latency: 32,
      rps: 2000,
      errorRate: 0.003,
      cpuUsage: 46,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-009',
    name: 'Database 009',
    type: 'Analytics Database',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 380,
    healthScore: 89,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 120 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'analytics', 'warehouse'],
    telemetry: {
      latency: 195,
      rps: 350,
      errorRate: 0.008,
      cpuUsage: 58,
      memoryUsage: 72,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-010',
    name: 'Database 010',
    type: 'Graph Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 340,
    healthScore: 78,
    status: 'failing',
    dependencies: [],
    lastModified: new Date(Date.now() - 1 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'graph', 'relationships'],
    telemetry: {
      latency: 85,
      rps: 250,
      errorRate: 0.065,
      cpuUsage: 92,
      memoryUsage: 88,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-003',
    name: 'Cache 003',
    type: 'Cache',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 165,
    healthScore: 96,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 84 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 3,
      rps: 16000,
      errorRate: 0.001,
      cpuUsage: 54,
      memoryUsage: 66,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-004',
    name: 'Cache 004',
    type: 'Cache',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 175,
    healthScore: 95,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 4,
      rps: 17000,
      errorRate: 0.002,
      cpuUsage: 59,
      memoryUsage: 69,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-005',
    name: 'Cache 005',
    type: 'Cache',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 160,
    healthScore: 93,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 60 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'memcached', 'performance'],
    telemetry: {
      latency: 5,
      rps: 14000,
      errorRate: 0.003,
      cpuUsage: 51,
      memoryUsage: 63,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-006',
    name: 'Cache 006',
    type: 'Cache',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 170,
    healthScore: 94,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 48 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 4,
      rps: 15500,
      errorRate: 0.002,
      cpuUsage: 56,
      memoryUsage: 68,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-007',
    name: 'Cache 007',
    type: 'Cache',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 155,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 36 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'tracing'],
    telemetry: {
      latency: 2,
      rps: 12000,
      errorRate: 0.001,
      cpuUsage: 48,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-003',
    name: 'Message Queue 003',
    type: 'Message Queue',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 140,
    healthScore: 95,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 120 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'async'],
    telemetry: {
      latency: 50,
      rps: 4800,
      errorRate: 0.005,
      cpuUsage: 48,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-004',
    name: 'Message Queue 004',
    type: 'Message Queue',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 145,
    healthScore: 92,
    status: 'degraded',
    dependencies: [],
    lastModified: new Date(Date.now() - 12 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'logging'],
    telemetry: {
      latency: 72,
      rps: 8000,
      errorRate: 0.018,
      cpuUsage: 68,
      memoryUsage: 75,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-005',
    name: 'Message Queue 005',
    type: 'Message Queue',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 138,
    healthScore: 93,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 96 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'async'],
    telemetry: {
      latency: 55,
      rps: 4500,
      errorRate: 0.007,
      cpuUsage: 45,
      memoryUsage: 55,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-006',
    name: 'Message Queue 006',
    type: 'Message Queue',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 142,
    healthScore: 90,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 84 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'analytics'],
    telemetry: {
      latency: 60,
      rps: 4000,
      errorRate: 0.01,
      cpuUsage: 52,
      memoryUsage: 61,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'config-store-001',
    name: 'Config Store 001',
    type: 'Config Store',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 95,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['config', 'storage'],
    telemetry: {
      latency: 15,
      rps: 5000,
      errorRate: 0.001,
      cpuUsage: 22,
      memoryUsage: 28,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'metrics-db-001',
    name: 'Metrics Database 001',
    type: 'Time Series Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 320,
    healthScore: 90,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 108 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['metrics', 'timeseries', 'prometheus'],
    telemetry: {
      latency: 145,
      rps: 1500,
      errorRate: 0.008,
      cpuUsage: 65,
      memoryUsage: 74,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'log-store-001',
    name: 'Log Store 001',
    type: 'Log Storage',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 410,
    healthScore: 89,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['logging', 'elasticsearch', 'storage'],
    telemetry: {
      latency: 120,
      rps: 15000,
      errorRate: 0.012,
      cpuUsage: 78,
      memoryUsage: 82,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'trace-store-001',
    name: 'Trace Store 001',
    type: 'Trace Storage',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 285,
    healthScore: 87,
    status: 'degraded',
    dependencies: [],
    lastModified: new Date(Date.now() - 9 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['tracing', 'jaeger', 'storage'],
    telemetry: {
      latency: 130,
      rps: 6500,
      errorRate: 0.028,
      cpuUsage: 71,
      memoryUsage: 78,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'audit-log-001',
    name: 'Audit Log 001',
    type: 'Audit Store',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 185,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 216 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['audit', 'logging', 'compliance'],
    telemetry: {
      latency: 45,
      rps: 1800,
      errorRate: 0.002,
      cpuUsage: 32,
      memoryUsage: 42,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
];

export const mockEdges = [
  // Gateway Layer - Entry Points
  { id: 'edge-1', source: 'svc-api-001', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 5, rps: 2500, errorRate: 0.02 } },
  { id: 'edge-2', source: 'svc-auth-002', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 5, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-3', source: 'svc-payment-010', target: 'gateway-002', type: 'HTTP/REST', telemetry: { latency: 6, rps: 3200, errorRate: 0.003 } },
  { id: 'edge-4', source: 'svc-order-004', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 5, rps: 1200, errorRate: 0.015 } },
  { id: 'edge-5', source: 'svc-billing-016', target: 'gateway-003', type: 'HTTP/REST', telemetry: { latency: 7, rps: 1000, errorRate: 0.025 } },
  { id: 'edge-6', source: 'svc-analytics-017', target: 'gateway-002', type: 'HTTP/REST', telemetry: { latency: 6, rps: 600, errorRate: 0.01 } },
  { id: 'edge-7', source: 'svc-recommendation-018', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 8, rps: 500, errorRate: 0.08 } },
  { id: 'edge-8', source: 'svc-export-019', target: 'gateway-004', type: 'HTTP/REST', telemetry: { latency: 9, rps: 200, errorRate: 0.04 } },

  // Database Connections
  { id: 'edge-9', source: 'svc-api-001', target: 'db-001', type: 'SQL', telemetry: { latency: 12, rps: 2500, errorRate: 0.02 } },
  { id: 'edge-10', source: 'svc-auth-002', target: 'db-002', type: 'SQL', telemetry: { latency: 11, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-11', source: 'svc-order-004', target: 'db-003', type: 'SQL', telemetry: { latency: 35, rps: 1200, errorRate: 0.015 } },
  { id: 'edge-12', source: 'svc-inv-005', target: 'db-004', type: 'SQL', telemetry: { latency: 28, rps: 600, errorRate: 0.01 } },
  { id: 'edge-13', source: 'svc-user-007', target: 'db-005', type: 'SQL', telemetry: { latency: 22, rps: 1500, errorRate: 0.008 } },
  { id: 'edge-14', source: 'svc-payment-010', target: 'db-006', type: 'SQL', telemetry: { latency: 15, rps: 3200, errorRate: 0.003 } },
  { id: 'edge-15', source: 'svc-admin-011', target: 'db-007', type: 'SQL', telemetry: { latency: 42, rps: 300, errorRate: 0.006 } },
  { id: 'edge-16', source: 'svc-report-006', target: 'db-analytics', type: 'SQL', telemetry: { latency: 250, rps: 200, errorRate: 0.005 } },
  { id: 'edge-17', source: 'svc-billing-016', target: 'db-008', type: 'SQL', telemetry: { latency: 18, rps: 800, errorRate: 0.012 } },
  { id: 'edge-18', source: 'svc-analytics-017', target: 'db-009', type: 'SQL', telemetry: { latency: 195, rps: 350, errorRate: 0.008 } },
  { id: 'edge-19', source: 'svc-recommendation-018', target: 'db-010', type: 'SQL', telemetry: { latency: 85, rps: 250, errorRate: 0.05 } },

  // Cache Connections
  { id: 'edge-20', source: 'svc-api-001', target: 'cache-001', type: 'Cache', telemetry: { latency: 3, rps: 2500, errorRate: 0.02 } },
  { id: 'edge-21', source: 'svc-inv-005', target: 'cache-002', type: 'Cache', telemetry: { latency: 4, rps: 600, errorRate: 0.01 } },
  { id: 'edge-22', source: 'svc-auth-002', target: 'cache-001', type: 'Cache', telemetry: { latency: 3, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-23', source: 'svc-user-007', target: 'cache-001', type: 'Cache', telemetry: { latency: 3, rps: 1500, errorRate: 0.008 } },
  { id: 'edge-24', source: 'svc-recommendation-018', target: 'cache-005', type: 'Cache', telemetry: { latency: 2, rps: 500, errorRate: 0.08 } },

  // Message Queue Connections
  { id: 'edge-25', source: 'svc-notif-003', target: 'queue-001', type: 'Message', telemetry: { latency: 45, rps: 450, errorRate: 0.45 } },
  { id: 'edge-26', source: 'svc-notif-003', target: 'queue-002', type: 'Message', telemetry: { latency: 65, rps: 450, errorRate: 0.45 } },
  { id: 'edge-27', source: 'svc-webhook-008', target: 'queue-001', type: 'Message', telemetry: { latency: 45, rps: 800, errorRate: 0.08 } },
  { id: 'edge-28', source: 'svc-webhook-008', target: 'queue-003', type: 'Message', telemetry: { latency: 65, rps: 800, errorRate: 0.08 } },
  { id: 'edge-29', source: 'svc-export-019', target: 'queue-005', type: 'Message', telemetry: { latency: 50, rps: 200, errorRate: 0.04 } },
  { id: 'edge-30', source: 'svc-billing-016', target: 'queue-002', type: 'Message', telemetry: { latency: 55, rps: 300, errorRate: 0.025 } },
  { id: 'edge-31', source: 'svc-analytics-017', target: 'queue-006', type: 'Message', telemetry: { latency: 60, rps: 400, errorRate: 0.01 } },

  // Service-to-Service Calls
  { id: 'edge-32', source: 'svc-order-004', target: 'svc-api-001', type: 'HTTP/REST', telemetry: { latency: 45, rps: 800, errorRate: 0.015 } },
  { id: 'edge-33', source: 'svc-order-004', target: 'svc-inv-005', type: 'HTTP/REST', telemetry: { latency: 62, rps: 600, errorRate: 0.015 } },
  { id: 'edge-34', source: 'svc-order-004', target: 'svc-payment-010', type: 'HTTP/REST', telemetry: { latency: 48, rps: 500, errorRate: 0.02 } },
  { id: 'edge-35', source: 'svc-payment-010', target: 'svc-api-001', type: 'HTTP/REST', telemetry: { latency: 48, rps: 2000, errorRate: 0.003 } },
  { id: 'edge-36', source: 'svc-user-007', target: 'svc-auth-002', type: 'HTTP/REST', telemetry: { latency: 52, rps: 1200, errorRate: 0.008 } },
  { id: 'edge-37', source: 'svc-api-001', target: 'svc-user-007', type: 'HTTP/REST', telemetry: { latency: 45, rps: 1500, errorRate: 0.02 } },
  { id: 'edge-38', source: 'svc-analytics-017', target: 'svc-api-001', type: 'HTTP/REST', telemetry: { latency: 50, rps: 350, errorRate: 0.008 } },
  { id: 'edge-39', source: 'svc-recommendation-018', target: 'svc-api-001', type: 'gRPC', telemetry: { latency: 75, rps: 250, errorRate: 0.08 } },
  { id: 'edge-40', source: 'svc-recommendation-018', target: 'svc-user-007', type: 'gRPC', telemetry: { latency: 65, rps: 200, errorRate: 0.08 } },
  { id: 'edge-41', source: 'svc-billing-016', target: 'svc-payment-010', type: 'HTTP/REST', telemetry: { latency: 55, rps: 600, errorRate: 0.025 } },
  { id: 'edge-42', source: 'svc-export-019', target: 'svc-report-006', type: 'HTTP/REST', telemetry: { latency: 60, rps: 180, errorRate: 0.04 } },

  // Vault/Secret Management
  { id: 'edge-43', source: 'svc-auth-002', target: 'vault-001', type: 'API', telemetry: { latency: 28, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-44', source: 'svc-payment-010', target: 'vault-002', type: 'API', telemetry: { latency: 29, rps: 2000, errorRate: 0.003 } },
  { id: 'edge-45', source: 'svc-billing-016', target: 'vault-001', type: 'API', telemetry: { latency: 30, rps: 500, errorRate: 0.01 } },

  // Search Index Connections
  { id: 'edge-46', source: 'svc-search-009', target: 'search-index-001', type: 'API', telemetry: { latency: 125, rps: 950, errorRate: 0.012 } },
  { id: 'edge-47', source: 'svc-api-001', target: 'search-index-001', type: 'API', telemetry: { latency: 110, rps: 800, errorRate: 0.015 } },

  // Observability Connections
  { id: 'edge-48', source: 'svc-logging-014', target: 'log-store-001', type: 'Streaming', telemetry: { latency: 75, rps: 8000, errorRate: 0.005 } },
  { id: 'edge-49', source: 'svc-logging-014', target: 'queue-004', type: 'Message', telemetry: { latency: 75, rps: 8000, errorRate: 0.005 } },
  { id: 'edge-50', source: 'svc-tracer-015', target: 'trace-store-001', type: 'Streaming', telemetry: { latency: 68, rps: 6500, errorRate: 0.004 } },
  { id: 'edge-51', source: 'svc-metrics-013', target: 'metrics-db-001', type: 'Streaming', telemetry: { latency: 145, rps: 400, errorRate: 0.018 } },
  { id: 'edge-52', source: 'svc-admin-011', target: 'audit-log-001', type: 'Streaming', telemetry: { latency: 89, rps: 300, errorRate: 0.006 } },

  // Config Management
  { id: 'edge-53', source: 'svc-config-012', target: 'config-store-001', type: 'API', telemetry: { latency: 15, rps: 5000, errorRate: 0.001 } },

  // Infrastructure Layer
  { id: 'edge-54', source: 'kube-001', target: 'db-001', type: 'Network', telemetry: { latency: 8, rps: 10000, errorRate: 0.003 } },
  { id: 'edge-55', source: 'kube-002', target: 'db-002', type: 'Network', telemetry: { latency: 9, rps: 9000, errorRate: 0.004 } },
  { id: 'edge-56', source: 'kube-003', target: 'db-003', type: 'Network', telemetry: { latency: 10, rps: 8500, errorRate: 0.003 } },
  { id: 'edge-57', source: 'gateway-001', target: 'lb-001', type: 'Network', telemetry: { latency: 2, rps: 15000, errorRate: 0.001 } },
  { id: 'edge-58', source: 'gateway-002', target: 'lb-001', type: 'Network', telemetry: { latency: 2, rps: 12000, errorRate: 0.002 } },
  { id: 'edge-59', source: 'gateway-003', target: 'lb-002', type: 'Network', telemetry: { latency: 2, rps: 8000, errorRate: 0.002 } },
  { id: 'edge-60', source: 'gateway-004', target: 'lb-002', type: 'Network', telemetry: { latency: 3, rps: 5000, errorRate: 0.003 } },
  { id: 'edge-61', source: 'service-mesh-001', target: 'gateway-001', type: 'Network', telemetry: { latency: 1, rps: 50000, errorRate: 0.0005 } },

  // Monitoring Infrastructure
  { id: 'edge-62', source: 'monitoring-001', target: 'metrics-db-001', type: 'Streaming', telemetry: { latency: 85, rps: 2000, errorRate: 0.005 } },
  { id: 'edge-63', source: 'logging-infra-001', target: 'log-store-001', type: 'Streaming', telemetry: { latency: 120, rps: 15000, errorRate: 0.008 } },
  { id: 'edge-64', source: 'alerting-001', target: 'metrics-db-001', type: 'API', telemetry: { latency: 95, rps: 1500, errorRate: 0.004 } },

  // Registry & CDN
  { id: 'edge-65', source: 'cdn-001', target: 'registry-001', type: 'HTTP/REST', telemetry: { latency: 12, rps: 50000, errorRate: 0.001 } },
  { id: 'edge-66', source: 'kube-001', target: 'registry-001', type: 'Network', telemetry: { latency: 150, rps: 500, errorRate: 0.001 } },
  { id: 'edge-67', source: 'kube-002', target: 'registry-001', type: 'Network', telemetry: { latency: 155, rps: 450, errorRate: 0.001 } },
];

export const mockPipelines = [
  {
    id: 'pipeline-1',
    name: 'Deploy Service 001',
    artifact: 'svc-api-001',
    status: 'success',
    commit: 'abc123def456ghi789',
    author: 'Developer Name',
    message: 'Optimize API response times',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-2',
    name: 'Deploy Service Auth 002',
    artifact: 'svc-auth-002',
    status: 'success',
    commit: 'xyz789abc123def456',
    author: 'Developer Name',
    message: 'Update security policies',
    timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-3',
    name: 'Deploy Service Notification 023',
    artifact: 'svc-notification-023',
    status: 'failed',
    commit: 'mno456pqr789stu123',
    author: 'Developer Name',
    message: 'Add event streaming support',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-4',
    name: 'Deploy Service Billing 016',
    artifact: 'svc-billing-016',
    status: 'success',
    commit: 'def789ghi123jkl456',
    author: 'Developer Name',
    message: 'Fix billing calculation logic',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-5',
    name: 'Deploy Database 010',
    artifact: 'db-010',
    status: 'failed',
    commit: 'vwx123yza456bcd789',
    author: 'Developer Name',
    message: 'Migrate to new schema',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-6',
    name: 'Deploy Service Recommendation 018',
    artifact: 'svc-recommendation-018',
    status: 'failed',
    commit: 'efg123hij456klm789',
    author: 'Developer Name',
    message: 'Update ML recommendation model',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
  },
  {
    id: 'pipeline-7',
    name: 'Deploy Service Export 019',
    artifact: 'svc-export-019',
    status: 'success',
    commit: 'nop123qrs456tuv789',
    author: 'Developer Name',
    message: 'Add parallel export processing',
    timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-8',
    name: 'Deploy Message Queue 004',
    artifact: 'queue-004',
    status: 'success',
    commit: 'uvw123xyz456abc789',
    author: 'Developer Name',
    message: 'Update queue consumer strategy',
    timestamp: new Date(Date.now() - 12 * 60 * 1000),
  },
  {
    id: 'pipeline-9',
    name: 'Deploy Trace Store 001',
    artifact: 'trace-store-001',
    status: 'failed',
    commit: 'hij123klm456nop789',
    author: 'Developer Name',
    message: 'Upgrade Jaeger version',
    timestamp: new Date(Date.now() - 9 * 60 * 1000),
  },
  {
    id: 'pipeline-10',
    name: 'Deploy API Gateway 004',
    artifact: 'gateway-004',
    status: 'failed',
    commit: 'tuy123vwx456yza789',
    author: 'Developer Name',
    message: 'Add new rate limiting rules',
    timestamp: new Date(Date.now() - 6 * 60 * 1000),
  },
];

export const mockAlerts = [
  {
    id: 'alert-1',
    resourceId: 'svc-notif-003',
    severity: 'critical',
    message: 'High error rate detected',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'alert-2',
    resourceId: 'queue-002',
    severity: 'warning',
    message: 'Queue depth increasing',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
  },
  {
    id: 'alert-3',
    resourceId: 'db-010',
    severity: 'critical',
    message: 'Database CPU usage exceeds 90%',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: 'alert-4',
    resourceId: 'svc-recommendation-018',
    severity: 'critical',
    message: 'Service error rate at 8%',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
  },
  {
    id: 'alert-5',
    resourceId: 'gateway-004',
    severity: 'warning',
    message: 'Latency spike detected',
    timestamp: new Date(Date.now() - 6 * 60 * 1000),
  },
  {
    id: 'alert-6',
    resourceId: 'trace-store-001',
    severity: 'warning',
    message: 'Error rate trending upward',
    timestamp: new Date(Date.now() - 9 * 60 * 1000),
  },
  {
    id: 'alert-7',
    resourceId: 'queue-004',
    severity: 'warning',
    message: 'Queue latency increased 40%',
    timestamp: new Date(Date.now() - 12 * 60 * 1000),
  },
  {
    id: 'alert-8',
    resourceId: 'svc-workflow-025',
    severity: 'warning',
    message: 'Workflow processing time exceeded SLA',
    timestamp: new Date(Date.now() - 4 * 60 * 1000),
  },
  {
    id: 'alert-9',
    resourceId: 'svc-billing-016',
    severity: 'warning',
    message: 'Billing service throughput degradation',
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
  },
  {
    id: 'alert-10',
    resourceId: 'svc-export-019',
    severity: 'warning',
    message: 'Export job queue depth at 85%',
    timestamp: new Date(Date.now() - 3 * 60 * 1000),
  },
];

export const mockForecasts = [
  {
    id: 'forecast-1',
    resourceId: 'svc-notif-003',
    riskLevel: 'critical',
    confidence: 95,
    explanation: 'Service showing degradation pattern. Error rate trending from 2% to 45% over 6 hours. Recommend immediate investigation of queue dependencies.',
    window: '1-2 hours',
    actionPlan: [
      'Review recent deployments to svc-notif-003 and queue dependencies',
      'Check queue-001 and queue-002 health metrics',
      'Analyze error logs for common failure patterns',
      'Consider scaling queue consumers or reducing message complexity',
      'If unresolved, prepare rollback strategy',
    ],
  },
  {
    id: 'forecast-2',
    resourceId: 'db-010',
    riskLevel: 'critical',
    confidence: 92,
    explanation: 'Graph Database experiencing resource saturation. CPU at 92%, Memory at 88%. Trend indicates will hit 100% within 30 minutes.',
    window: '15-30 minutes',
    actionPlan: [
      'Immediately scale vertical resources for db-010',
      'Enable connection pooling if not already active',
      'Analyze and optimize slow queries affecting svc-recommendation-018',
      'Consider query result caching at application layer',
      'Prepare emergency connection throttling if scaling fails',
    ],
  },
  {
    id: 'forecast-3',
    resourceId: 'svc-recommendation-018',
    riskLevel: 'critical',
    confidence: 88,
    explanation: 'ML service experiencing cascading failure. High latency (85ms), 8% error rate detected. Likely due to db-010 bottleneck.',
    window: '20-40 minutes',
    actionPlan: [
      'Resolve upstream db-010 capacity issues first',
      'Implement circuit breaker pattern for database calls',
      'Add fallback to cached recommendations',
      'Scale svc-recommendation-018 replicas temporarily',
      'Consider shedding low-priority recommendation requests',
    ],
  },
  {
    id: 'forecast-4',
    resourceId: 'queue-004',
    riskLevel: 'high',
    confidence: 85,
    explanation: 'Message queue experiencing increased latency (72ms) and error rate (1.8%). Logging service may be overwhelmed.',
    window: '45-90 minutes',
    actionPlan: [
      'Scale logging-infra-001 to handle increased throughput',
      'Review svc-logging-014 consumer processing speed',
      'Consider implementing message batching',
      'Add dead letter queue monitoring',
      'Gradually reduce non-critical log verbosity',
    ],
  },
  {
    id: 'forecast-5',
    resourceId: 'gateway-004',
    riskLevel: 'high',
    confidence: 82,
    explanation: 'API Gateway 004 showing latency spike (8ms average). Capacity approaching limits with 5000 RPS.',
    window: '1-2 hours',
    actionPlan: [
      'Scale gateway-004 instances',
      'Review rate limiting rules on gateway-004',
      'Check for traffic anomalies or DDoS patterns',
      'Consider traffic migration to gateway-001 or gateway-003',
      'Monitor connection pool exhaustion',
    ],
  },
  {
    id: 'forecast-6',
    resourceId: 'trace-store-001',
    riskLevel: 'high',
    confidence: 80,
    explanation: 'Trace storage degrading. Error rate at 2.8% and climbing. May impact tracing for all services using svc-tracer-015.',
    window: '2-3 hours',
    actionPlan: [
      'Increase retention policy to balance storage vs performance',
      'Optimize Jaeger index rebuild frequency',
      'Review trace volume from high-throughput services',
      'Consider sampling trace collection for non-critical services',
      'Check underlying disk I/O on trace-store-001',
    ],
  },
  {
    id: 'forecast-7',
    resourceId: 'svc-billing-016',
    riskLevel: 'medium',
    confidence: 78,
    explanation: 'Billing service throughput declining. Error rate at 2.5%, approaching SLA violation.',
    window: '2-4 hours',
    actionPlan: [
      'Review recent changes to svc-billing-016 or dependencies',
      'Check db-008 connection pool limits',
      'Monitor vault-001 for access latency',
      'Scale svc-billing-016 processing threads',
      'Implement billing request queuing for peak periods',
    ],
  },
  {
    id: 'forecast-8',
    resourceId: 'svc-workflow-025',
    riskLevel: 'medium',
    confidence: 76,
    explanation: 'Workflow orchestration latency increased. Processing time 245ms vs SLA of 200ms.',
    window: '2-5 hours',
    actionPlan: [
      'Profile workflow step execution times',
      'Check queue-003 and queue-005 latency',
      'Review db-008 query performance',
      'Implement workflow step parallelization where possible',
      'Consider workflow step caching for repeated patterns',
    ],
  },
];

export const assistantQA = [];

export const workspaceInfo = {
  name: 'Cloud Dependency Atlas',
  description: 'Multi-layer infrastructure visualization and analysis platform',
  lastUpdated: new Date(),
  subscriptionId: 'sub-cda-001',
  lastSync: new Date(),
};

export const historicalSnapshots = [
  { 
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), 
    nodeCount: 55, 
    errorRate: 0.008,
    resources: mockResources // Full resource list at this point
  },
  { 
    timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000), 
    nodeCount: 56, 
    errorRate: 0.009,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000), 
    nodeCount: 56, 
    errorRate: 0.011,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000), 
    nodeCount: 57, 
    errorRate: 0.013,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000), 
    nodeCount: 58, 
    errorRate: 0.015,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000), 
    nodeCount: 59, 
    errorRate: 0.018,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000), 
    nodeCount: 60, 
    errorRate: 0.022,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), 
    nodeCount: 61, 
    errorRate: 0.028,
    resources: mockResources
  },
  { 
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000), 
    nodeCount: 61, 
    errorRate: 0.032,
    resources: mockResources
  },
  { 
    timestamp: new Date(), 
    nodeCount: 61, 
    errorRate: 0.035,
    resources: mockResources
  },
];

export const exampleGraphDefinition = `# Example Infrastructure Declaration
# Use this format to define your topology

layers:
  application:
    - name: Service API 001
      type: Web App
      region: Region A
      dependencies: [Database 001, Cache 001]
  
  infrastructure:
    - name: API Gateway 001
      type: Gateway
      region: Region A
  
  data:
    - name: Database 001
      type: SQL Database
      region: Region A
`;
