// ============================================
// MOCK DATA - Synthetic Example Infrastructure
// ============================================
// This file contains synthetic mock data for demonstration purposes.
// All service names, team names, costs, and metrics are completely fictional
// and generated for visualization examples only.
//
// DO NOT commit real infrastructure data to public repositories.
// DO NOT include:
// - Real team names or personnel information
// - Real service names or internal architecture
// - Real cost data
// - Real API keys, tokens, or secrets
// - Real email addresses
// - Real region/datacenter information
// ============================================

export const mockResources = [
  // ===== APPLICATION LAYER (15 services) =====
  {
    id: 'svc-api-001',
    name: 'Service API 001',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Alpha',
    cost30d: 450,
    healthScore: 98,
    status: 'healthy',
    dependencies: ['db-001', 'cache-001', 'gateway-001'],
    lastModified: new Date(Date.now() - 2 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['api', 'critical', 'service'],
    telemetry: {
      latency: 45,
      rps: 2500,
      errorRate: 0.02,
      cpuUsage: 78,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-auth-002',
    name: 'Service Auth 002',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Beta',
    cost30d: 280,
    healthScore: 99,
    status: 'healthy',
    dependencies: ['db-002', 'vault-001', 'gateway-001'],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['auth', 'security', 'critical'],
    telemetry: {
      latency: 38,
      rps: 1800,
      errorRate: 0.005,
      cpuUsage: 32,
      memoryUsage: 41,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-notif-003',
    name: 'Service Notify 003',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Gamma',
    cost30d: 180,
    healthScore: 72,
    status: 'failing',
    dependencies: ['queue-001', 'queue-002'],
    lastModified: new Date(Date.now() - 1 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['notification', 'messaging'],
    telemetry: {
      latency: 520,
      rps: 450,
      errorRate: 0.45,
      cpuUsage: 5,
      memoryUsage: 15,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-order-004',
    name: 'Service Order 004',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Delta',
    cost30d: 320,
    healthScore: 95,
    status: 'healthy',
    dependencies: ['db-003', 'svc-api-001', 'svc-inv-005'],
    lastModified: new Date(Date.now() - 4 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['orders', 'critical', 'business'],
    telemetry: {
      latency: 62,
      rps: 1200,
      errorRate: 0.015,
      cpuUsage: 45,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-inv-005',
    name: 'Service Inventory 005',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Epsilon',
    cost30d: 220,
    healthScore: 88,
    status: 'healthy',
    dependencies: ['db-004', 'cache-002'],
    lastModified: new Date(Date.now() - 5 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['inventory', 'service'],
    telemetry: {
      latency: 95,
      rps: 600,
      errorRate: 0.01,
      cpuUsage: 34,
      memoryUsage: 48,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-report-006',
    name: 'Service Report 006',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Zeta',
    cost30d: 150,
    healthScore: 91,
    status: 'healthy',
    dependencies: ['db-analytics', 'cache-003'],
    lastModified: new Date(Date.now() - 8 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['analytics', 'reporting'],
    telemetry: {
      latency: 180,
      rps: 200,
      errorRate: 0.005,
      cpuUsage: 28,
      memoryUsage: 35,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-user-007',
    name: 'Service User 007',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Beta',
    cost30d: 190,
    healthScore: 96,
    status: 'healthy',
    dependencies: ['db-005', 'cache-001', 'svc-auth-002'],
    lastModified: new Date(Date.now() - 3 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['users', 'critical'],
    telemetry: {
      latency: 52,
      rps: 1500,
      errorRate: 0.008,
      cpuUsage: 42,
      memoryUsage: 54,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-webhook-008',
    name: 'Service Webhook 008',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Gamma',
    cost30d: 130,
    healthScore: 93,
    status: 'degraded',
    dependencies: ['queue-001', 'queue-003'],
    lastModified: new Date(Date.now() - 6 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['webhooks', 'integration'],
    telemetry: {
      latency: 340,
      rps: 800,
      errorRate: 0.08,
      cpuUsage: 56,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-search-009',
    name: 'Service Search 009',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Delta',
    cost30d: 240,
    healthScore: 89,
    status: 'healthy',
    dependencies: ['search-index-001', 'cache-004'],
    lastModified: new Date(Date.now() - 12 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['search', 'service'],
    telemetry: {
      latency: 125,
      rps: 950,
      errorRate: 0.012,
      cpuUsage: 67,
      memoryUsage: 71,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-payment-010',
    name: 'Service Payment 010',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Epsilon',
    cost30d: 380,
    healthScore: 99,
    status: 'healthy',
    dependencies: ['db-006', 'gateway-002', 'vault-002'],
    lastModified: new Date(Date.now() - 24 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['payment', 'critical', 'financial'],
    telemetry: {
      latency: 48,
      rps: 3200,
      errorRate: 0.003,
      cpuUsage: 81,
      memoryUsage: 68,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-admin-011',
    name: 'Service Admin 011',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Zeta',
    cost30d: 165,
    healthScore: 92,
    status: 'healthy',
    dependencies: ['db-007', 'audit-log-001'],
    lastModified: new Date(Date.now() - 48 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['admin', 'management'],
    telemetry: {
      latency: 89,
      rps: 300,
      errorRate: 0.006,
      cpuUsage: 22,
      memoryUsage: 38,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-config-012',
    name: 'Service Config 012',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Alpha',
    cost30d: 95,
    healthScore: 97,
    status: 'healthy',
    dependencies: ['config-store-001', 'cache-005'],
    lastModified: new Date(Date.now() - 36 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['config', 'service'],
    telemetry: {
      latency: 15,
      rps: 5000,
      errorRate: 0.001,
      cpuUsage: 18,
      memoryUsage: 24,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-metrics-013',
    name: 'Service Metrics 013',
    type: 'Web App',
    region: 'Region B',
    owner: 'Team Gamma',
    cost30d: 210,
    healthScore: 85,
    status: 'healthy',
    dependencies: ['metrics-db-001', 'cache-006'],
    lastModified: new Date(Date.now() - 18 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['metrics', 'monitoring'],
    telemetry: {
      latency: 145,
      rps: 400,
      errorRate: 0.018,
      cpuUsage: 52,
      memoryUsage: 59,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-logging-014',
    name: 'Service Logging 014',
    type: 'Web App',
    region: 'Region C',
    owner: 'Team Delta',
    cost30d: 175,
    healthScore: 94,
    status: 'healthy',
    dependencies: ['log-store-001', 'queue-004'],
    lastModified: new Date(Date.now() - 9 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['logging', 'observability'],
    telemetry: {
      latency: 75,
      rps: 8000,
      errorRate: 0.005,
      cpuUsage: 64,
      memoryUsage: 72,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'svc-tracer-015',
    name: 'Service Tracer 015',
    type: 'Web App',
    region: 'Region A',
    owner: 'Team Epsilon',
    cost30d: 145,
    healthScore: 96,
    status: 'healthy',
    dependencies: ['trace-store-001', 'cache-007'],
    lastModified: new Date(Date.now() - 14 * 60 * 60 * 1000),
    layer: 'application',
    tags: ['tracing', 'observability'],
    telemetry: {
      latency: 68,
      rps: 6500,
      errorRate: 0.004,
      cpuUsage: 58,
      memoryUsage: 61,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },

  // ===== INFRASTRUCTURE LAYER (12 services) =====
  {
    id: 'gateway-001',
    name: 'API Gateway 001',
    type: 'API Gateway',
    region: 'Region A',
    owner: 'Infra Team',
    cost30d: 280,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['gateway', 'critical', 'ingress'],
    telemetry: {
      latency: 5,
      rps: 15000,
      errorRate: 0.001,
      cpuUsage: 45,
      memoryUsage: 38,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'gateway-002',
    name: 'API Gateway 002',
    type: 'API Gateway',
    region: 'Region B',
    owner: 'Infra Team',
    cost30d: 270,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['gateway', 'critical', 'ingress'],
    telemetry: {
      latency: 6,
      rps: 12000,
      errorRate: 0.002,
      cpuUsage: 42,
      memoryUsage: 36,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'lb-001',
    name: 'Load Balancer 001',
    type: 'Load Balancer',
    region: 'Region A',
    owner: 'Infra Team',
    cost30d: 120,
    healthScore: 100,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 240 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['load-balancer', 'critical'],
    telemetry: {
      latency: 2,
      rps: 20000,
      errorRate: 0.0,
      cpuUsage: 35,
      memoryUsage: 28,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'kube-001',
    name: 'Kubernetes Cluster 001',
    type: 'Orchestration',
    region: 'Region A',
    owner: 'Platform Team',
    cost30d: 450,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['kubernetes', 'orchestration', 'critical'],
    telemetry: {
      latency: 8,
      rps: 10000,
      errorRate: 0.003,
      cpuUsage: 62,
      memoryUsage: 71,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'kube-002',
    name: 'Kubernetes Cluster 002',
    type: 'Orchestration',
    region: 'Region B',
    owner: 'Platform Team',
    cost30d: 420,
    healthScore: 96,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 120 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['kubernetes', 'orchestration', 'critical'],
    telemetry: {
      latency: 9,
      rps: 9000,
      errorRate: 0.004,
      cpuUsage: 68,
      memoryUsage: 74,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'registry-001',
    name: 'Container Registry 001',
    type: 'Registry',
    region: 'Region A',
    owner: 'Platform Team',
    cost30d: 85,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 216 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['registry', 'storage'],
    telemetry: {
      latency: 150,
      rps: 500,
      errorRate: 0.001,
      cpuUsage: 25,
      memoryUsage: 32,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'vault-001',
    name: 'Secrets Vault 001',
    type: 'Secrets Management',
    region: 'Region A',
    owner: 'Team Iota',
    cost30d: 95,
    healthScore: 100,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 300 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['secrets', 'security', 'critical'],
    telemetry: {
      latency: 28,
      rps: 4000,
      errorRate: 0.0,
      cpuUsage: 18,
      memoryUsage: 22,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'vault-002',
    name: 'Secrets Vault 002',
    type: 'Secrets Management',
    region: 'Region B',
    owner: 'Team Iota',
    cost30d: 95,
    healthScore: 100,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 312 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['secrets', 'security', 'critical'],
    telemetry: {
      latency: 29,
      rps: 3800,
      errorRate: 0.0,
      cpuUsage: 16,
      memoryUsage: 21,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'monitoring-001',
    name: 'Monitoring System 001',
    type: 'Monitoring',
    region: 'Region A',
    owner: 'DevOps Team',
    cost30d: 220,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 96 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['monitoring', 'observability', 'critical'],
    telemetry: {
      latency: 85,
      rps: 2000,
      errorRate: 0.005,
      cpuUsage: 48,
      memoryUsage: 52,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'logging-infra-001',
    name: 'Logging Infrastructure 001',
    type: 'Logging',
    region: 'Region B',
    owner: 'DevOps Team',
    cost30d: 310,
    healthScore: 95,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 72 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['logging', 'observability'],
    telemetry: {
      latency: 120,
      rps: 15000,
      errorRate: 0.008,
      cpuUsage: 71,
      memoryUsage: 78,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cdn-001',
    name: 'Content Delivery 001',
    type: 'CDN',
    region: 'Global',
    owner: 'Infra Team',
    cost30d: 350,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'infrastructure',
    tags: ['cdn', 'performance', 'critical'],
    telemetry: {
      latency: 12,
      rps: 50000,
      errorRate: 0.001,
      cpuUsage: 38,
      memoryUsage: 44,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },

  // ===== DATA LAYER (14 services) =====
  {
    id: 'db-001',
    name: 'Database 001',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 520,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 240 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'critical'],
    telemetry: {
      latency: 12,
      rps: 5000,
      errorRate: 0.001,
      cpuUsage: 52,
      memoryUsage: 68,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-002',
    name: 'Database 002',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 480,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 264 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'critical'],
    telemetry: {
      latency: 11,
      rps: 4500,
      errorRate: 0.0005,
      cpuUsage: 48,
      memoryUsage: 65,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-003',
    name: 'Database 003',
    type: 'SQL Database',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 440,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 35,
      rps: 2800,
      errorRate: 0.003,
      cpuUsage: 44,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-004',
    name: 'Database 004',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 390,
    healthScore: 96,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 216 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 28,
      rps: 2000,
      errorRate: 0.002,
      cpuUsage: 38,
      memoryUsage: 58,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-005',
    name: 'Database 005',
    type: 'SQL Database',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 410,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 22,
      rps: 3200,
      errorRate: 0.001,
      cpuUsage: 41,
      memoryUsage: 60,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-006',
    name: 'Database 006',
    type: 'SQL Database',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 540,
    healthScore: 99,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 288 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql', 'financial'],
    telemetry: {
      latency: 15,
      rps: 6000,
      errorRate: 0.0005,
      cpuUsage: 58,
      memoryUsage: 72,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-007',
    name: 'Database 007',
    type: 'SQL Database',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 370,
    healthScore: 95,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 312 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['database', 'sql'],
    telemetry: {
      latency: 42,
      rps: 1200,
      errorRate: 0.005,
      cpuUsage: 32,
      memoryUsage: 52,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-001',
    name: 'Cache 001',
    type: 'Cache',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 180,
    healthScore: 98,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 120 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 3,
      rps: 20000,
      errorRate: 0.001,
      cpuUsage: 62,
      memoryUsage: 74,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'cache-002',
    name: 'Cache 002',
    type: 'Cache',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 170,
    healthScore: 97,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 96 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['cache', 'redis', 'performance'],
    telemetry: {
      latency: 4,
      rps: 18000,
      errorRate: 0.002,
      cpuUsage: 58,
      memoryUsage: 70,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-001',
    name: 'Message Queue 001',
    type: 'Message Queue',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 140,
    healthScore: 94,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 168 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'async'],
    telemetry: {
      latency: 45,
      rps: 5000,
      errorRate: 0.008,
      cpuUsage: 44,
      memoryUsage: 56,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'queue-002',
    name: 'Message Queue 002',
    type: 'Message Queue',
    region: 'Region B',
    owner: 'Data Team',
    cost30d: 135,
    healthScore: 92,
    status: 'degraded',
    dependencies: [],
    lastModified: new Date(Date.now() - 48 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['queue', 'messaging', 'async'],
    telemetry: {
      latency: 65,
      rps: 4200,
      errorRate: 0.015,
      cpuUsage: 52,
      memoryUsage: 62,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'search-index-001',
    name: 'Search Index 001',
    type: 'Search Engine',
    region: 'Region A',
    owner: 'Data Team',
    cost30d: 210,
    healthScore: 91,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 144 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['search', 'elasticsearch', 'indexing'],
    telemetry: {
      latency: 110,
      rps: 2500,
      errorRate: 0.012,
      cpuUsage: 68,
      memoryUsage: 76,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
  {
    id: 'db-analytics',
    name: 'Analytics Database',
    type: 'Analytics',
    region: 'Region C',
    owner: 'Data Team',
    cost30d: 290,
    healthScore: 88,
    status: 'healthy',
    dependencies: [],
    lastModified: new Date(Date.now() - 192 * 60 * 60 * 1000),
    layer: 'data',
    tags: ['analytics', 'warehouse', 'bigdata'],
    telemetry: {
      latency: 250,
      rps: 150,
      errorRate: 0.02,
      cpuUsage: 72,
      memoryUsage: 85,
    },
    blastRadius: {
      isFailed: false,
      failureTime: null,
      upstreamImpacted: [],
      downstreamImpacted: [],
    },
  },
];

export const mockEdges = [
  { id: 'edge-1', source: 'svc-api-001', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 5, rps: 2500, errorRate: 0.02 } },
  { id: 'edge-2', source: 'svc-auth-002', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 5, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-3', source: 'svc-payment-010', target: 'gateway-002', type: 'HTTP/REST', telemetry: { latency: 6, rps: 3200, errorRate: 0.003 } },
  { id: 'edge-4', source: 'svc-order-004', target: 'gateway-001', type: 'HTTP/REST', telemetry: { latency: 5, rps: 1200, errorRate: 0.015 } },
  { id: 'edge-5', source: 'svc-api-001', target: 'db-001', type: 'SQL', telemetry: { latency: 12, rps: 2500, errorRate: 0.02 } },
  { id: 'edge-6', source: 'svc-api-001', target: 'cache-001', type: 'Cache', telemetry: { latency: 3, rps: 2500, errorRate: 0.02 } },
  { id: 'edge-7', source: 'svc-auth-002', target: 'db-002', type: 'SQL', telemetry: { latency: 11, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-8', source: 'svc-auth-002', target: 'vault-001', type: 'API', telemetry: { latency: 28, rps: 1800, errorRate: 0.005 } },
  { id: 'edge-9', source: 'svc-order-004', target: 'db-003', type: 'SQL', telemetry: { latency: 35, rps: 1200, errorRate: 0.015 } },
  { id: 'edge-10', source: 'svc-order-004', target: 'svc-api-001', type: 'HTTP/REST', telemetry: { latency: 45, rps: 800, errorRate: 0.015 } },
  { id: 'edge-11', source: 'svc-order-004', target: 'svc-inv-005', type: 'HTTP/REST', telemetry: { latency: 62, rps: 600, errorRate: 0.015 } },
  { id: 'edge-12', source: 'svc-payment-010', target: 'svc-api-001', type: 'HTTP/REST', telemetry: { latency: 48, rps: 2000, errorRate: 0.003 } },
  { id: 'edge-13', source: 'svc-user-007', target: 'svc-auth-002', type: 'HTTP/REST', telemetry: { latency: 52, rps: 1200, errorRate: 0.008 } },
  { id: 'edge-14', source: 'kube-001', target: 'db-001', type: 'Network', telemetry: { latency: 8, rps: 10000, errorRate: 0.003 } },
  { id: 'edge-15', source: 'kube-002', target: 'db-002', type: 'Network', telemetry: { latency: 9, rps: 9000, errorRate: 0.004 } },
  { id: 'edge-16', source: 'svc-notif-003', target: 'queue-001', type: 'Message', telemetry: { latency: 45, rps: 450, errorRate: 0.45 } },
  { id: 'edge-17', source: 'svc-notif-003', target: 'queue-002', type: 'Message', telemetry: { latency: 65, rps: 450, errorRate: 0.45 } },
  { id: 'edge-18', source: 'svc-inv-005', target: 'db-004', type: 'SQL', telemetry: { latency: 28, rps: 600, errorRate: 0.01 } },
  { id: 'edge-19', source: 'svc-inv-005', target: 'cache-002', type: 'Cache', telemetry: { latency: 4, rps: 600, errorRate: 0.01 } },
  { id: 'edge-20', source: 'svc-report-006', target: 'db-analytics', type: 'SQL', telemetry: { latency: 250, rps: 200, errorRate: 0.005 } },
  { id: 'edge-21', source: 'svc-search-009', target: 'search-index-001', type: 'API', telemetry: { latency: 125, rps: 950, errorRate: 0.012 } },
  { id: 'edge-22', source: 'svc-webhook-008', target: 'queue-001', type: 'Message', telemetry: { latency: 45, rps: 800, errorRate: 0.08 } },
  { id: 'edge-23', source: 'svc-webhook-008', target: 'queue-003', type: 'Message', telemetry: { latency: 65, rps: 800, errorRate: 0.08 } },
  { id: 'edge-24', source: 'svc-logging-014', target: 'log-store-001', type: 'Streaming', telemetry: { latency: 75, rps: 8000, errorRate: 0.005 } },
  { id: 'edge-25', source: 'svc-logging-014', target: 'queue-004', type: 'Message', telemetry: { latency: 75, rps: 8000, errorRate: 0.005 } },
  { id: 'edge-26', source: 'svc-tracer-015', target: 'trace-store-001', type: 'Streaming', telemetry: { latency: 68, rps: 6500, errorRate: 0.004 } },
  { id: 'edge-27', source: 'svc-metrics-013', target: 'metrics-db-001', type: 'Streaming', telemetry: { latency: 145, rps: 400, errorRate: 0.018 } },
  { id: 'edge-28', source: 'svc-config-012', target: 'config-store-001', type: 'API', telemetry: { latency: 15, rps: 5000, errorRate: 0.001 } },
  { id: 'edge-29', source: 'svc-api-001', target: 'svc-user-007', type: 'HTTP/REST', telemetry: { latency: 45, rps: 1500, errorRate: 0.02 } },
  { id: 'edge-30', source: 'svc-user-007', target: 'db-005', type: 'SQL', telemetry: { latency: 22, rps: 1500, errorRate: 0.008 } },
  { id: 'edge-31', source: 'svc-payment-010', target: 'vault-002', type: 'API', telemetry: { latency: 29, rps: 2000, errorRate: 0.003 } },
  { id: 'edge-32', source: 'svc-admin-011', target: 'db-007', type: 'SQL', telemetry: { latency: 42, rps: 300, errorRate: 0.006 } },
  { id: 'edge-33', source: 'svc-admin-011', target: 'audit-log-001', type: 'Streaming', telemetry: { latency: 89, rps: 300, errorRate: 0.006 } },
  { id: 'edge-34', source: 'gateway-001', target: 'lb-001', type: 'Network', telemetry: { latency: 2, rps: 15000, errorRate: 0.001 } },
  { id: 'edge-35', source: 'gateway-002', target: 'lb-001', type: 'Network', telemetry: { latency: 2, rps: 12000, errorRate: 0.002 } },
  { id: 'edge-36', source: 'monitoring-001', target: 'metrics-db-001', type: 'Streaming', telemetry: { latency: 85, rps: 2000, errorRate: 0.005 } },
  { id: 'edge-37', source: 'logging-infra-001', target: 'log-store-001', type: 'Streaming', telemetry: { latency: 120, rps: 15000, errorRate: 0.008 } },
  { id: 'edge-38', source: 'cdn-001', target: 'registry-001', type: 'HTTP/REST', telemetry: { latency: 12, rps: 50000, errorRate: 0.001 } },
  { id: 'edge-39', source: 'kube-001', target: 'registry-001', type: 'Network', telemetry: { latency: 150, rps: 500, errorRate: 0.001 } },
];

export const mockPipelines = [
  {
    id: 'pipeline-1',
    name: 'Deploy Service 001',
    artifact: 'svc-api-001',
    status: 'success',
    commit: 'abc123def456ghi789',
    author: 'Developer Name',
    message: 'Optimize API response times',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'pipeline-2',
    name: 'Deploy Service Auth 002',
    artifact: 'svc-auth-002',
    status: 'success',
    commit: 'xyz789abc123def456',
    author: 'Developer Name',
    message: 'Update security policies',
    timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000),
  },
];

export const mockAlerts = [
  {
    id: 'alert-1',
    resourceId: 'svc-notif-003',
    severity: 'critical',
    message: 'High error rate detected',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'alert-2',
    resourceId: 'queue-002',
    severity: 'warning',
    message: 'Queue depth increasing',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
  },
];

export const mockForecasts = [
  {
    id: 'forecast-1',
    resourceId: 'svc-notif-003',
    riskLevel: 'critical',
    confidence: 95,
    explanation: 'Service showing degradation pattern. Recommend immediate investigation.',
    window: '1-2 hours',
  },
];

export const assistantQA = [];

export const workspaceInfo = {
  name: 'Enterprise Observability Center',
  description: 'Multi-layer infrastructure visualization and analysis platform',
  lastUpdated: new Date(),
};

export const historicalSnapshots = [
  { timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), nodeCount: 40, errorRate: 0.012 },
  { timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000), nodeCount: 41, errorRate: 0.009 },
  { timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000), nodeCount: 41, errorRate: 0.011 },
];

export const exampleGraphDefinition = `# Example Infrastructure Declaration
# Use this format to define your topology

layers:
  application:
    - name: Service API 001
      type: Web App
      region: Region A
      dependencies: [Database 001, Cache 001]
  
  infrastructure:
    - name: API Gateway 001
      type: Gateway
      region: Region A
  
  data:
    - name: Database 001
      type: SQL Database
      region: Region A
`;
